{
 "title": "Serv1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Гистограмма",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "my_space_grpc_my_app_histogram_response_time_seconds_bucket"
    }
   ]
  },
  {
   "title": "Количество входящих запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(my_space_grpc_my_app_requests_total[5s])"
    }
   ]
  },
  {
   "title": "Количество ответов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(my_space_grpc_my_app_responses_total[5s])"
    }
   ]
  }
 ]
}